### ISSUE TITLE
Error when using Redstone particle

### ISSUE THREAD

**Issue by twk1024** [lukasvdgaag/SkyWarsReloaded#15]
`[11:12:15] [Craft Scheduler Thread - 19/WARN]: [Skywars] Plugin Skywars v5.4.2 generated an exception while executing task 32446
java.lang.IllegalArgumentException: Particle REDSTONE requires data, null provided
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.craftbukkit.v1_16_R3.CraftParticle.toNMS(CraftParticle.java:146) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.spawnParticle(CraftPlayer.java:1955) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.spawnParticle(CraftPlayer.java:1942) ~[patched_1.16.5.jar:git-Paper-469]
	at com.walrusone.skywarsreloaded.nms.v1_16_R3.NMSHandler.sendParticles(NMSHandler.java:43) ~[?:?]
	at com.walrusone.skywarsreloaded.utilities.Util$2.run(Util.java:217) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-469]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-469]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]`

When the player who selected Redstone particle joins the skywars arena, it starts making this error.
Other particles have no problem.

**Comment by TechnicallyCoded** [comment]
If you haven't already, please update to the latest Skywars version. If the issue persists, reply to this issue. Otherwise I will close this issue in 7 days.

**Comment by TechnicallyCoded** [comment]
No reply.
