### ISSUE TITLE
plugin no longer worlds on 1.18

### ISSUE THREAD

**Issue by Budderman18** [lukasvdgaag/SkyWarsReloaded#33]
Displays this error upon enabling:

[22:34:17] [Server thread/INFO]: [Skywars] Enabling Skywars v5.6.1
[22:34:17] [Server thread/ERROR]: [Skywars] Could not find support for this CraftBukkit version: v1_18_R1. Now disabling the plugin!
[22:34:17] [Server thread/ERROR]: Error occurred while enabling Skywars v5.6.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.walrusone.skywarsreloaded.SkyWarsReloaded.onDisable(SkyWarsReloaded.java:406) ~[SkyWarsReloaded 5.6.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at com.walrusone.skywarsreloaded.SkyWarsReloaded.onEnable(SkyWarsReloaded.java:165) ~[SkyWarsReloaded 5.6.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-82]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-82]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.walrusone.skywarsreloaded.listeners.IconMenuController.create(String, java.util.ArrayList, com.walrusone.skywarsreloaded.menus.IconMenu$OptionClickEventHandler)" because the return value of "com.walrusone.skywarsreloaded.SkyWarsReloaded.getIC()" is null
	at com.walrusone.skywarsreloaded.menus.ArenasMenu.<init>(ArenasMenu.java:69) ~[SkyWarsReloaded 5.6.1.jar:?]
	at com.walrusone.skywarsreloaded.game.GameMap.<clinit>(GameMap.java:54) ~[SkyWarsReloaded 5.6.1.jar:?]
	... 14 more

**Comment by lukasvdgaag** [comment]
We are aware that the plugin does not work on 1.18. This is simply because we are working on a complete rewrite of the plugin. This is why we will no longer be updating the current version (v5).

**Comment by TechnicallyCoded** [comment]
Hey, as a temporary resolution, you can just use the viaversion plugin. The major difference between 1.17 and 1.18 is world generation which is something that has no part in the skywars gamemode. This will allow you to have a perfectly functional 1.18 server without actually running 1.18 behind the scenes. Remember that Log4J updates have been pushed for Paper and Purpur for 1.17 so the newest builds should be safe to run.

**Comment by finnie2006** [comment]
can the V5 not get updated for the latest release, because it looks like v6 is still taking a while

**Comment by TechnicallyCoded** [comment]
This is an outdated thread. It works in 1.18 latest release. We will probs do the same for 1.19.

**Comment by finnie2006** [comment]
😂

**Comment by finnie2006** [comment]
👍🏻
