### ISSUE TITLE
Player can't join the match

### ISSUE THREAD

**Issue by deka9584** [lukasvdgaag/SkyWarsReloaded#4]
Sometimes when a player chooses a map using the join menu it will not be teleported into the game.

This error appears in the console:

`[17:39:05] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Skywars v5.3.3
java.lang.NullPointerException: null
    at com.walrusone.skywarsreloaded.game.cages.Cage.setGlassColor(Cage.java:76) ~[?:?]
    at com.walrusone.skywarsreloaded.game.TeamCard.spawnCage(TeamCard.java:132) ~[?:?]
    at com.walrusone.skywarsreloaded.game.TeamCard.sendReservation(TeamCard.java:109) ~[?:?]
    at com.walrusone.skywarsreloaded.game.GameMap.addPlayers(GameMap.java:578) ~[?:?]
    at com.walrusone.skywarsreloaded.menus.JoinSingleMenu.lambda$new$1(JoinSingleMenu.java:318) ~[?:?]
    at com.walrusone.skywarsreloaded.menus.IconMenu.onInventoryClick(IconMenu.java:86) ~[?:?]
    at com.walrusone.skywarsreloaded.listeners.IconMenuController.onInventoryClick(IconMenuController.java:84) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor371.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-390]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-390]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-390]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2384) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-390]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-390]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

I use PaperMC 390 (MC 1.15.2)
Multiverse-Core is installed and the lobby world is the main world of the server.

**Comment by TechnicallyCoded** [comment]
It seems as though some player's data does not have the cage color option set. This is not checked for and creates an error. For the time being, try re-setting your cage selection in the options menu.

Also, could I get the following information:
Are you using a MySQL database or normal configuration system?

**Comment by deka9584** [comment]
Thank for answare.
No, I use a normal configuration. There is only one server for skywars and MySQL database isn't connected to the plugin.

**Comment by lukasvdgaag** [comment]
> No, I use a normal configuration.
Could you tell me what the value of the `glasscolor` option is in the playerData file of your in-game player UUID? You can find this file in `/plugins/Skywars/playerData/<yourUUID>.yml`.

**Comment by deka9584** [comment]
On many player data files is set to "none" but the problem seems to occur randomly.

**Comment by lukasvdgaag** [comment]
> On many player data files is set to "none" but the problem seems to occur randomly.

And so was the one that you got the error from?

**Comment by deka9584** [comment]
Yes, also on my uuid glass color is set to "none" and I had the problem.
When it happens it is enough to leave the server and re-enter to be able to join the match.

**Comment by lukasvdgaag** [comment]
@deka9584 would you mind joining our Discord server and shoot me a message so I can send you a beta file to test out? The link is https://gaagjescraft.net/discord.
You can also just add me: GCNT#0001

**Comment by deka9584** [comment]
Ok I will join later.
I will also try the new version.

**Comment by TechnicallyCoded** [comment]
A fix was provided in the latest github push. Should be fixed in the next spigot release.
