### ISSUE TITLE
When you select 2 particle effects adding arens will cause an error

### ISSUE THREAD

**Issue by Coquettishpig** [lukasvdgaag/SkyWarsReloaded#44]
[18:05:57 WARN]: [Skywars] Plugin Skywars v5.6.9 generated an exception while executing task 12968
java.lang.IllegalArgumentException: Particle REDSTONE requires data, null provided
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftParticle.toNMS(CraftParticle.java:172) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2382) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2369) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.walrusone.skywarsreloaded.nms.v1_18_R2.NMSHandler.sendParticles(NMSHandler.java:56) ~[SkyWarsReloaded 5.6.9.jar:?]
        at com.walrusone.skywarsreloaded.utilities.Util$2.run(Util.java:221) ~[SkyWarsReloaded 5.6.9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TechnicallyCoded** [comment]
Trying to use 1.8 particles in 1.13+ - You can find a list of the new ones on the Minecraft wiki

Please also update your version of skywars https://my.gcnt.net from our website :)
