### ISSUE TITLE
[Error] Updated from FlamePaper 1.8.8 to Dionyisus 1.12.2

### ISSUE THREAD

**Issue by TH3N3WN00B** [lukasvdgaag/SkyWarsReloaded#51]
As title says, i updated from 1.8.8 to 1.12.2 and got the next error:

```
[21:48:15 ERROR]: Error occurred while enabling Skywars v5.6.13 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at com.walrusone.skywarsreloaded.menus.playeroptions.WinSoundOption.loadPlayerOptions(WinSoundOption.java:105) ~[?:?]
        at com.walrusone.skywarsreloaded.managers.PlayerOptionsManager.<init>(PlayerOptionsManager.java:58) ~[?:?]
        at com.walrusone.skywarsreloaded.SkyWarsReloaded.load(SkyWarsReloaded.java:457) ~[?:?]
        at com.walrusone.skywarsreloaded.SkyWarsReloaded.onEnable(SkyWarsReloaded.java:281) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:398) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:445) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:406) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:344) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:295) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:633) ~[patched_1.12.2.jar:git-Dionysus-"a87ca7a"]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[21:48:15 INFO]: [Skywars] Disabling Skywars v5.6.13
```

Full log: 
https://paste.gg/p/anonymous/6273d7d4334f4f3293cd202093224bda

**Comment by xism4** [comment]
> ]
> [21:48:15 INFO]: [Skywars] Disabling Skywars v5.6.13

java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 1

Some menu
